version: '3'
services:
  redis:
    image: redis
    ports:
     - "6379:6379"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
     - "5432:5432"
  testdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: testpassword 
      POSTGRES_USER: testuser
      POSTGRES_DB: testdb
    ports:
     - "9999:5432"
  app:
    build: .
    command: bash -c "source /app/docker-env-set.sh && /urlshort"
    restart: always
    ports:
     - "8888:8888"
    depends_on:
     - db
     - testdb
     - redis